Bkarosenyou/snsproject/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from .views import SignupView


app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(),name='logout'),
    path('signup/', SignupView.as_view(),name='signup'),
]

Bkarosenyou/snsproject/snsapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.TopPageView.as_view(),name='index'),
    
    path('coment/', views.ComentView.as_view(),name='coment'),
    path('reply/<int:pk>', views.ReplyView.as_view(),name='reply'),
    
    path('profile/<int:ids>',views.profileView,name='profile'),
    path('profilesetting/<int:pk>',views.ProfileSettingView.as_view(),name='profile-setting'),
    
    path('search/',views.SearchView.as_view(),name='search'),
    path('test/',views.Test.as_view(),name='test'),
    path('setting/',views.SettingView.as_view(),name='setting'),
    path('delete/<int:pk>',views.deletecomment,name='delete'),
    path('detail/<int:pk>',views.DetailView.as_view(),name='detail'),
    path('evaluation/<int:pk>',views.evaluationview, name='evaluation'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bkarosenyou/snsproject/snsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('snsapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bkarosenyou/snsproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>SNS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'sns/css/reset.css' %}">
<link rel="stylesheet" href="{% static 'sns/css/style.css' %}">
</head>
<body>
    <div class="bunkatu">
        <div>
            <nav id="menubar">
                <header class="header">
                <div class="navtext-container">
                    <div class="navtext">カスタマイズ</div>
                </div>
                <input type="checkbox" class="menu-btn" id="menu-btn">
                <label for="menu-btn" class="menu-icon"><span class="navicon"></span></label>
                    <ul class="menu">
                        <li><a href="#contact">デフォルト</a></li>
                        <li><a href="#home">イラスト</a></li>
                        <li><a href="#skills">ハンドメイド</a></li>
                        <li><a href="#projects">動画</a></li>
                        <li><a href="#contact">ゲーム</a></li>
                        <li><a href="#contact">+カスタマイズ</a></li>
                    </ul>
            
                </header>
                    <ul class="navlink">
                        <li class="up"><a href="{% url 'index' %}">ホーム</a></li>
                        <li class="up"><a href="{% url 'test' %}">検索</a></li>
                        <li class="up"><a href="recruit.html">通知</a></li>
                        <li class="up"><a href="company.html">リスト</a></li>
                        {% if request.user.is_authenticated %}
                        <li class="up"><a href="{% url 'profile' request.user.id %}">プロフィール</a></li>
                        {% endif %}
                        <li class="up"><a href="{% url 'setting' %}">設定</a></li>
                    </ul>
                    <ul class="navlink2">
                        <li class="downn"><a href="{% url 'coment' %}">コメントする</a></li>
                        <li class="downn"><a href="recruit.html">自分のプロフィールに飛ぶ</a></li>
                    </ul>
            </nav>
        </div>
        <div class="coment">
            {% block content %}{% endblock %}
    <!-- <div class="navbar-nav d-flex flex-row">
        {% if request.user.is_authenticated %}
        <a class="nav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>
        {% else %}
        <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
        <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">会員登録</a>
        {% endif %}
    </div> -->
        </div>
    </div>
</body>
</html>